mariadb:
  build: ./.templates/mariadb/.
  container_name: mariadb
  environment:
    - TZ=Etc/UTC
    - PUID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - PGID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
    - MYSQL_ROOT_PASSWORD=%randomAdminPassword%
    - MYSQL_DATABASE=default
    - MYSQL_USER=mariadbuser
    - MYSQL_PASSWORD=%randomPassword%
  volumes:
    - ./volumes/mariadb/config:/config
    - ./volumes/mariadb/db_backup:/backup
  ports:
    - "3306:3306"
  restart: unless-stopped

