domoticz:
  container_name: domoticz
  image: linuxserver/domoticz:stable
  ports:
    - "8083:8080"
    - "6144:6144"
    - "1443:1443"
  volumes:
    - ./volumes/domoticz/data:/config
  restart: unless-stopped
  network_mode: bridge
  environment:
    - PUID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - PGID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
    # - TZ=
    # - WEBROOT=domoticz

