gitea:
  container_name: gitea
  image: "kunde21/gitea-arm:latest"
  restart: unless-stopped
  ports:
    - "7920:3000/tcp"
    - "2222:22/tcp"
  environment:
    - USER_UID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - USER_GID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
  volumes:
    - ./volumes/gitea/data:/data
    - /etc/timezone:/etc/timezone:ro

