homer:
  image: b4bz/homer:latest
  container_name: homer
  environment:
    - UID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - GID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
  volumes:
    - ./volumes/homer/assets:/www/assets
  ports:
    - "8881:8080"
  restart: unless-stopped

