homebridge:
  container_name: homebridge
  image: oznu/homebridge:latest
  restart: unless-stopped
  environment:
    - TZ=Etc/UTC
    - PGID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
    - PUID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - HOMEBRIDGE_CONFIG_UI=1
    - HOMEBRIDGE_CONFIG_UI_PORT=8581
  volumes:
    - ./volumes/homebridge:/homebridge
  network_mode: host

