heimdall:
  image: ghcr.io/linuxserver/heimdall
  container_name: heimdall
  environment:
    - PUID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - PGID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
    - TZ=Europe/Paris
  volumes:
    - ./volumes/heimdall/config:/config
  ports:
    - 8880:80
    - 8883:443
  restart: unless-stopped

