  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
      - PGID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
      - UMASK_SET=022
      - WEBUI_PORT=15080
    volumes:
      - ./volumes/qbittorrent/config:/config
      - ./volumes/qbittorrent/downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "15080:15080"
      - "1080:1080"

