transmission:
  image: linuxserver/transmission
  container_name: transmission
  environment:
    - PUID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - PGID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
    - TZ=Etc/UTC
  volumes:
    - ./volumes/transmission/config:/config
    - ./volumes/transmission/downloads:/downloads
    - ./volumes/transmission/watch:/watch
  ports:
    - "9091:9091"
    - "51413:51413"
    - "51413:51413/udp"
  restart: unless-stopped

