plex:
  image: linuxserver/plex
  container_name: plex
  network_mode: host
  environment:
    - PUID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - PGID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
    - VERSION=docker
  volumes:
    - ./volumes/plex/config:/config
    - ./volumes/plex/transcode:/transcode
  restart: unless-stopped

