python:
  container_name: python
  build: ./services/python/.
  restart: unless-stopped
  environment:
    - TZ=Etc/UTC
    - IOTSTACK_UID=${IOTSTACK_UID:?IOTSTACK_UID must be defined in ~/IOTstack/.env}
    - IOTSTACK_GID=${IOTSTACK_GID:?IOTSTACK_GID must be defined in ~/IOTstack/.env}
  # ports:
  #   - "external:internal"
  volumes:
    - ./volumes/python/app:/usr/src/app

